### ISSUE TITLE
gif captcha

### ISSUE THREAD

**Issue by wahello** [mbi/django-simple-captcha#184]
简单的静态图越来越无法对抗OCR了, 希望能升级未gif来应对一下

**Comment by mbi** [comment]
[Google translate for the non-chinese speaking](https://translate.google.com/#view=home&op=translate&sl=auto&tl=en&text=%E7%AE%80%E5%8D%95%E7%9A%84%E9%9D%99%E6%80%81%E5%9B%BE%E8%B6%8A%E6%9D%A5%E8%B6%8A%E6%97%A0%E6%B3%95%E5%AF%B9%E6%8A%97OCR%E4%BA%86%2C%20%E5%B8%8C%E6%9C%9B%E8%83%BD%E5%8D%87%E7%BA%A7%E6%9C%AAgif%E6%9D%A5%E5%BA%94%E5%AF%B9%E4%B8%80%E4%B8%8B):

> Simple static images are increasingly unable to resist OCR, I hope to upgrade the non-gif to deal with it


Good idea, PR's welcome, although I don't really see how a GIF could be of any help here, since it's just an uncompressed stream of bitmap images.

**Comment by 9mido** [comment]
@mbi The movement of the letters / numbers / background would probably help. Here are some examples I found:

https://www.jeffreythompson.org/blog/2014/07/17/animated-captcha/

https://devrant.com/rants/197411/first-time-ive-seen-a-captcha-like-this-it-takes-it-to-a-whole-new-level

https://tsnetimages-technospot2.netdna-ssl.com/blogs/img/animated-captcha.gif

https://tenor.com/view/captcha-samjolteon-text-bouncing-animation-gif-14766701

http://blog.vappic.com/2012/01/different-4d-captcha-model-experiments.html

https://tenor.com/view/captcha-code-glitch-letters-numbers-gif-16291128

https://visuall.net/wp-content/uploads/2013/09/2013-025-Animation01.gif

https://www.drupal.org/files/aspam-captcha.gif

As a side note, is there any way to refresh the captcha without refreshing the page like this?

https://issues.liferay.com/secure/attachment/268396/RefreshCaptcha.gif

http://www.aspdotnet-pools.com/2017/03/ajax-mvc-captcha-validation-with-reload.html

**Comment by mbi** [comment]
I went through all of those examples, and IMO for all of them (except for maybe [this one](https://visuall.net/wp-content/uploads/2013/09/2013-025-Animation01.gif)), if a bot extracted a single frame from the gif  it wouldn't be a harder challenge than if it only had that single frame to start with.

And at the same time, it gets harder / more annoying for humans.

So this sound like a no-no to me, I think I'll close.
